Tolk 1749 --> master
navikt/crm-hot pull request #1025
Opened 2021-12-10 14:55 UTC by ebelegu

Opprettet flyt og action som lar formidler svare på inkomne sms.

2021-12-10 18:30 UTC, chfosli commented
```
TYPE   PROJECT PATH                                                          PROBLEM
─────  ────────────────────────────────────────────────────────────────────  ──────────────────────────────────────────────────────────────────────
Error  force-app/main/default/layouts/SMS__c-HOT SMS Layout.layout-meta.xml  In field: QuickAction - no QuickAction named SMS__c.Reply_on_SMS found
```

2021-12-13 13:53 UTC, EirikFladby requested changes
Mangler Quick Action 
https://github.com/navikt/crm-hot/pull/1025#issuecomment-991200131

2021-12-17 11:00 UTC, vmjelde approved these changes

2021-12-17 12:47 UTC, EirikFladby approved these changes

2021-12-17 13:01 UTC, merged