TOLK-1799 --> master
navikt/crm-hot pull request #1060
Opened 2022-01-13 11:40 UTC by EdvardBrekke

TODO:
* Deletion policy

2022-01-13 14:10 UTC, vmjelde requested changes
Her må API name på feltene endres.
Feltene på request trenger IKKE HOT-prefiks, ettersom objektet eies av oss ("HOT_Request__c").
Feltene på ServiceAppointment MÅ ha HOT-prefiks, ettersom det er standard objekt.

2022-01-13 14:10 UTC, vmjelde commented on force-app/main/triggers/classes/HOT_RequestHandler.cls
> +    }
Må utvides til å håndtere forespørsler fra community. Se kommentar over

2022-01-13 14:10 UTC, vmjelde commented on force-app/main/triggers/classes/HOT_WorkOrderHandler.cls
> +    }
Samme kommentarene for RequestHandler gjelder også her.
Må håndtere opprettelse fra Community, og navn på lister kan forbedres.

2022-01-13 18:52 UTC, vmjelde requested changes
Husk å oppdatere permsets når du bytter navn på felter.

HOT_Admin skal ha tilgang til alle felter.

Klarte ikke å få formelfeltet til å fi true i riktig situasjon

2022-01-13 18:52 UTC, vmjelde commented on force-app/main/default/objects/HOT_Request__c/fields/IsHideTextFields__c.field-meta.xml
> +    >IF(TEXT(SeriesEndDate__c) &lt;&gt; NULL, TODAY() &gt;= (SeriesEndDate__c + 365), TODAY() &gt;= (DATEVALUE(CreatedDate)  + 365))</formula>
Testa litt, men fikk ikke denne til å funke..

2022-01-13 18:52 UTC, vmjelde commented on force-app/main/default/permissionsets/HOT_Tolk_Bruker_Plus.permissionset-meta.xml
> +    </fieldPermissions>
Må også ha tilgang til Request-feltene.

Bruker Plus skal ha AKKURAT de samme tilgangene som Bruker.

2022-01-14 10:00 UTC, EdvardBrekke commented on force-app/main/default/objects/HOT_Request__c/fields/IsHideTextFields__c.field-meta.xml
> +    >IF(TEXT(SeriesEndDate__c) &lt;&gt; NULL, TODAY() &gt;= (SeriesEndDate__c + 365), TODAY() &gt;= (DATEVALUE(CreatedDate)  + 365))</formula>
Ikke? Jeg får true på feltet hvis SeriesEndDate er over ett år siden. Hvordan tester du?

2022-01-18 11:24 UTC, vmjelde requested changes

2022-01-18 11:24 UTC, vmjelde commented on force-app/main/default/classes/HOT_UpdateExistingRecords.cls
> +            'SELECT Subject__c, UserSubject__c, Description__c, UserDescription__c, (SELECT Subject, HOT_UserSubject__c, Description, HOT_UserDescription__c FROM HOT_Request__c.Work_Orders__r) FROM H
Legg til et filter-sjekk her. På at User-feltene er null og standard felter ikke er null.

2022-01-18 15:10 UTC, vmjelde approved these changes

2022-01-18 15:11 UTC, merged