Tolk 1842 --> master
navikt/crm-hot pull request #1101
Opened 2022-02-11 14:46 UTC by ebelegu

https://jira.adeo.no/browse/TOLK-1842

Imlemented setArchiveAsOwner for R, SA, WO and SMS.

2022-02-22 09:03 UTC, EirikFladby requested changes

2022-02-22 09:03 UTC, EirikFladby commented on force-app/main/triggers/classes/HOT_ServiceAppointmentHandler.cls
> +                serviceAppointment.HOT_IsHideServiceApointment__c == true
"== true" kan fjernes

2022-02-22 09:03 UTC, EirikFladby commented on force-app/main/triggers/classes/HOT_ServiceAppointmentHandler.cls
> +        QueueSobject archive = [SELECT QueueId, Queue.Name FROM QueueSobject WHERE Queue.Name = 'HOT Arkiv' LIMIT 1];
Fjerne Queue.Name

2022-02-22 09:03 UTC, EirikFladby commented on force-app/main/triggers/classes/HOT_ServiceAppointmentHandlerTest.cls
> +            SELECT Id, Owner.Name
Select heller OwnerId enn Owner.Name

2022-02-22 09:03 UTC, EirikFladby commented on force-app/main/triggers/classes/HOT_WorkOrderHandler.cls
> +        List<WorkOrder> changeOwnerToArchive = new List<WorkOrder>();
Navn på liste

2022-02-22 09:03 UTC, EirikFladby commented on force-app/main/triggers/classes/HOT_WorkOrderHandler.cls
> +                workOrder.HOT_IsHideWorkOrder__c == true
== true kan fjernes

2022-02-22 09:03 UTC, EirikFladby commented on force-app/main/triggers/classes/HOT_WorkOrderHandler.cls
> +        QueueSobject archive = [SELECT QueueId, Queue.Name FROM QueueSobject WHERE Queue.Name = 'HOT Arkiv' LIMIT 1];
Queue.Name kan fjernes fra select

2022-02-22 09:03 UTC, EirikFladby commented on force-app/main/triggers/classes/HOT_WorkOrderHandlerTest.cls
> +        WorkOrder workOrderUpdated = [SELECT Id, Owner.Name FROM WorkOrder WHERE Id = :workOrder.Id LIMIT 1];
Select OwnerId istedenfor Owner.Name

2022-03-09 09:59 UTC, vmjelde requested changes

2022-03-09 09:59 UTC, vmjelde commented on force-app/main/triggers/classes/HOT_RequestHandler.cls
> +    }
Skulle vi laget en felles metode i HOT_Utility.cls, som fungerer for alle SOBJECTS?

2022-03-09 09:59 UTC, vmjelde commented on force-app/main/triggers/classes/HOT_ServiceAppointmentHandler.cls
> +    }
Generalisere og flytte til HOT_Utility?

2022-03-14 08:51 UTC, vmjelde approved these changes

2022-03-14 10:52 UTC, merged