Assigninterestedresource flow err fix
navikt/crm-hot pull request #1154
Opened 2022-03-10 10:46 UTC by EirikFladby

2022-03-10 12:26 UTC, vmjelde requested changes

2022-03-10 12:26 UTC, vmjelde commented on force-app/main/triggers/classes/HOT_AssignedResourceHandler.cls
> +                serviceAppointmentsToUpdate.put(serviceAppointments.get(assignedResource.ServiceAppointmentId).Id, serviceAppointments.get(assignedResource.ServiceAppointmentId));
assignedResource.ServiceAppointmentId er vel det samme som serviceAppointments.get(assignedResource.ServiceAppointmentId).Id? Unødvendig å hente ut via map?

2022-03-10 12:26 UTC, vmjelde commented on force-app/main/triggers/classes/HOT_AssignedResourceHandler.cls
> +                SELECT Id, HOT_IsFreelanceInterpreter__c, HOT_IsEmployedInterpreter__c, HOT_ServiceTerritory__r.Id
Kan vel bare hente ut HOT_ServiceTerritory__c, trenger ikke __r,Id. Eller ga det et varsel om at Id ikke er ServiceTerritory?

2022-03-10 12:26 UTC, vmjelde commented on force-app/main/triggers/classes/HOT_AssignedResourceHandler.cls
> +                serviceAppointmentsToUpdate.put(serviceAppointments.get(assignedResource.ServiceAppointmentId).Id, serviceAppointments.get(assignedResource.ServiceAppointmentId));
serviceAppointments.get(assignedResource.ServiceAppointmentId).Id = assignedResource.ServiceAppointmentId

2022-03-10 12:26 UTC, vmjelde commented on force-app/main/triggers/classes/HOT_AssignedResourceHandler.cls
>          for (AssignedResource assignedResource : assignedResources) {
Kanskje det er veldig fint om vi tar vare på currentServiceAppointment, og bare endrer på den? Så legge den i mappet? Blir litt mer lettleselig. Kan gjøre det med serviceResource også, kanskje?
Hvordan sjekker vi da om de har blitt endret? kan man sjekke saMap.get(id) == currentSA?

2022-03-10 13:13 UTC, EirikFladby commented on force-app/main/triggers/classes/HOT_AssignedResourceHandler.cls
> +                serviceAppointmentsToUpdate.put(serviceAppointments.get(assignedResource.ServiceAppointmentId).Id, serviceAppointments.get(assignedResource.ServiceAppointmentId));
Haha, helt rett

2022-03-10 13:33 UTC, EirikFladby commented on force-app/main/triggers/classes/HOT_AssignedResourceHandler.cls
>          for (AssignedResource assignedResource : assignedResources) {
Ja, kan gjøre det mer lesbart, men kan ikke sjekke saMap.get(id) == currentSA, da de refererer til samme record som alltid er like.

2022-03-14 08:18 UTC, vmjelde approved these changes

2022-03-14 08:18 UTC, merged