Tolk 1795 - Som tolkebruker skal jeg miste tilgangen til info på bestilling etter 1 år
navikt/crm-hot pull request #1193
Opened 2022-04-07 09:35 UTC by EirikFladby

https://jira.adeo.no/browse/TOLK-1795

2022-04-07 10:05 UTC, vmjelde requested changes
Oppdaterer du UpdateExistingRecords.cls til å sette HOT_Interpreters__c for eksisterende records?

2022-04-20 08:17 UTC, vmjelde commented on force-app/main/triggers/classes/HOT_ServiceAppointmentHandler.cls
> +            if (serviceAppointment.Status != 'Scheduled' ||
Jo. Hvis ikke vil denne kjøre hver gang SA redigeres og status != scheduled

2022-04-26 12:31 UTC, EdvardBrekke approved these changes

2022-04-27 08:16 UTC, vmjelde approved these changes

2022-04-27 09:35 UTC, EirikFladby commented on force-app/main/default/classes/HOT_InterpreterOnWorkOrderService.cls
> +        workOrder.HOT_Interpreters__c += serviceAppointment.HOT_ServiceResource__r.Name + screenInterpreter + ', ';
Sikker på at denne ikke blir null hvis workOrder.HOT_Interpreters__c ikke har noen verdi enda?

2022-04-27 10:32 UTC, vmjelde commented on force-app/main/default/classes/HOT_InterpreterOnWorkOrderService.cls
> +        workOrder.HOT_Interpreters__c += serviceAppointment.HOT_ServiceResource__r.Name + screenInterpreter + ', ';
Burde kanskje ha en sjekk på det ja. Jeg legger inn

2022-04-28 09:11 UTC, merged