Fjerner EventType og OverrideRate på Request --> master
navikt/crm-hot pull request #1366
Opened 2022-09-12 10:38 UTC by EdvardBrekke

2022-09-12 11:08 UTC, vmjelde requested changes

2022-09-12 11:08 UTC, vmjelde commented on force-app/main/default/objects/HOT_Request__c/fields/EventType__c.field-meta.xml
> -</CustomField>
Tror det er best om vi bare fjerner det fra front-end i første omgang. Om roboten refererer til feltet, og vi fjerner det, kan det hende at noe tryner.. Men pakken installeres jo med -t DeprecateOnly, så feltet blir ikke slettet fra Orgen.. 
Men det fjernes fra permissionsettet til RPA, og det kan ikke referere til et felt som ikke eksisterer. Så vi må nok beholde feltet.
Tenkte høyt...

2022-09-12 11:08 UTC, vmjelde commented on force-app/main/default/objects/HOT_Request__c/fields/HOT_OverrideRate__c.field-meta.xml
> -</CustomField>
Må beholde feltet. Se kommentar over.

2022-09-12 11:08 UTC, vmjelde commented on force-app/main/default/permissionsets/HOT_Tolk_Formidler.permissionset-meta.xml
> -    </fieldPermissions>
Denne skal vi vel ha?

2022-09-12 11:08 UTC, vmjelde commented on force-app/main/default/permissionsets/HOT_Tolk_OEBS_Faktura_RPA.permissionset-meta.xml
> -    </recordTypeVisibilities>
Tenker dette permsettet kan beholde tilgangen til feltene.

2022-09-12 11:51 UTC, EdvardBrekke commented on force-app/main/default/permissionsets/HOT_Tolk_Formidler.permissionset-meta.xml
> -    </fieldPermissions>
Aner ikke hvorfor denne kom med

2022-09-12 11:55 UTC, EdvardBrekke commented on force-app/main/default/objects/HOT_Request__c/fields/HOT_OverrideRate__c.field-meta.xml
> -</CustomField>
👍🏻

2022-09-12 11:55 UTC, EdvardBrekke commented on force-app/main/default/permissionsets/HOT_Tolk_Formidler.permissionset-meta.xml
> -    </fieldPermissions>
Lagt tilbake nå

2022-09-12 11:55 UTC, EdvardBrekke commented on force-app/main/default/permissionsets/HOT_Tolk_OEBS_Faktura_RPA.permissionset-meta.xml
> -    </recordTypeVisibilities>
👍🏻

2022-09-13 06:08 UTC, vmjelde approved these changes

2022-09-15 11:23 UTC, merged