Tolk 1583 v6
navikt/crm-hot pull request #1378
Opened 2022-09-20 06:13 UTC by olsenrasmus

https://jira.adeo.no/browse/TOLK-1583

2022-09-20 06:38 UTC, vmjelde requested changes
Bare et par småting igjen!

2022-09-20 06:38 UTC, vmjelde commented on force-app/main/default/classes/HOT_UpdateExistingRecords.cls
> +
Nice. Burde kanskje også sjekke at HOT_Company__c (feltet på SA) != null i SOQL spørringen også.

2022-09-20 06:38 UTC, vmjelde commented on force-app/main/default/objectTranslations/ServiceAppointment-no/ServiceAppointment-no.objectTranslation-meta.xml
>          <value>Oppdrag</value>
Denne skal ikke oppdateres

2022-09-20 06:38 UTC, vmjelde commented on force-app/main/default/objects/ServiceAppointment/fields/HOT_Company__c.field-meta.xml
> +    <relationshipName>Service_Appointments</relationshipName>
RelationshipName burde være HOT_ServiceAppointmentsCompany, eller HOT_CompanyServiceAppointments
Siste er vel best

2022-09-20 08:05 UTC, olsenrasmus commented on force-app/main/default/objects/ServiceAppointment/fields/HOT_Company__c.field-meta.xml
> +    <relationshipName>Service_Appointments</relationshipName>
Går det altså fint bare å endre kun her i denne filen?

2022-09-20 08:11 UTC, vmjelde commented on force-app/main/default/objects/ServiceAppointment/fields/HOT_Company__c.field-meta.xml
> +    <relationshipName>Service_Appointments</relationshipName>
Jupp. Kjør på

2022-09-20 13:02 UTC, vmjelde requested changes

2022-09-20 13:02 UTC, vmjelde commented on force-app/main/default/objectTranslations/ServiceAppointment-no/ServiceAppointment-no.objectTranslation-meta.xml
> -</CustomObjectTranslation>
Beklager. Var uklar her.
Det skal ikke bli gjort noen endringer på denne fila. Her har du slettet den.

2022-09-20 13:02 UTC, vmjelde commented on force-app/main/default/classes/HOT_UpdateExistingRecords.cls
>          HOT_InterpreterOnWorkOrderService.setInterpreterOnWorkOrder(workOrderMap.keySet());
Var kanskje litt uklar her.

Foreslår at du og Jan Robert ser litt på batch-klassen sammen.
Ga han et par tips i stad

2022-09-21 08:58 UTC, olsenrasmus commented on force-app/main/default/objects/ServiceAppointment/fields/HOT_Company__c.field-meta.xml
> +    <relationshipName>Service_Appointments</relationshipName>
Fikk feilmeldinger på alle testene helt til jeg endret dette navnet i en annen fil også, men tror det er good nå. Alle testene ble grønne

2022-09-21 11:27 UTC, vmjelde requested changes

2022-09-21 11:27 UTC, vmjelde commented on force-app/main/default/classes/HOT_UpdateExistingRecords.cls
> +            'SELECT Id, HOT_Request__r.Company__c FROM ServiceAppointment WHERE  HOT_Request__r.Company__c != null'
Må hente ut HOT_Company__c også.
Fint om du også sjekker at HOT_Company__c == null

2022-09-21 11:27 UTC, vmjelde commented on force-app/main/default/classes/HOT_UpdateExistingRecords.cls
> +            if(sa.HOT_Company__c!=null){
burde vel sjekke sa.HOT_Company__c == null

2022-09-21 11:57 UTC, vmjelde approved these changes

2022-09-22 08:17 UTC, merged