Tolk 1952 - nytt felt avbestilt
navikt/crm-hot pull request #1405
Opened 2022-10-06 06:51 UTC by olsenrasmus

https://jira.adeo.no/browse/TOLK-1952

2022-10-10 07:27 UTC, olsenrasmus commented
**Med community scratchOrg:** 

- Sjekke at det står "Avbestilt" istedetfor "Avlyst" på alle nivåer
- Se om oversettelse av status er korrekt (skal stå avbestilt på cancelled på):
            Work Order
            Work Order Line Item
            Service Appointment
            Interested Resource

- Sjekke at all funksjonalitet i forhold til å opprette bestilling og avlyse bestilling fungerer, og sjekk at det ikke står avlys noe sted i popupbokser eller tilbakemeldinger. Sjekk også om eventuelt setninger er feilformulert:
          Lag nye bestillinger med serie og avbestill dem.
          Lag nye bestillinger og avbestill dem.
          Sjekk at "avlyst/avbestilt"- ikonet kommer opp på bestillinger du har avlyst
          Flow HOT_UpdateChildsFromRequest.flow-meta.xml:
                      Lag en forespørsel.
                      Avlys forespørselen
                      Start debug av flowen
                      Lim inn recordId til flow og sjekk at "Denne funksjonaliteten kan IKKE benyttes når forespørselen har status 
 Avbestilt eller Annullert" kommer opp

OBS: Når det kommer til tolk skal det stå "avlys/avlyst"
OBS: Når det kommer til filen HOT_ChangeServiceAppointmentStatus så er det noe galt med denne flowen i forhold til samme flow i UATHOT.

2022-10-13 07:48 UTC, JanRobertNav requested changes

2022-10-13 07:48 UTC, JanRobertNav commented on force-app/main/default/objectTranslations/HOT_InterestedResource__c-no/WorkOrderCanceledDate__c.fieldTranslation-meta.xml
> +    <label>Avbestiltdato</label>
skulle det vært et mellomrom her?

2022-10-13 07:48 UTC, JanRobertNav commented on force-app/main/notification/classes/HOT_ServiceAppointmentNotification.cls
> +            ' AvlyAvbestilt'
Her skulle det vel bare stått 'Avbestilt'?

2022-10-13 07:48 UTC, JanRobertNav commented on force-app/main/notification/classes/HOT_ServiceAppointmentNotificationTest.cls
> +        //Avbestiøt på vegne av bruker
Avbestilt

2022-10-13 08:00 UTC, JanRobertNav approved these changes

2023-12-12 09:34 UTC, closed without merging