Tolk 2008 - Formidler å kunne se om en bruker er død
navikt/crm-hot pull request #1421
Opened 2022-10-18 11:58 UTC by olsenrasmus

Formidler skal kunne se om bruker er død inne på forespørsel. Det er laget ny controller på Request.
Om bruker er død vil det komme et rødt banner på forespørsel som sier dette.

2022-10-18 12:06 UTC, olsenrasmus commented
**Hva er gjort: **
Formidler skal kunne se om bruker er død inne på forespørsel. Det er laget ny controller på Request.
Om bruker er død vil det komme et rødt banner på forespørsler som bruker har som sier dette.

**Testing: **

1. Sjekk at du har permissions til å se INT_IsDeceased__c feltet på Person. (HOT_Admin)
2. Legg til INT_IsDeceased__c på page layout på HOT Person slik at du enkelt kan velge om person er død eller ikke.
3. Gå inn på en Account og gå inn på en av hans forespørsler. Sjekk at det ikke er noe rødt banner som sier at bruker er død.
4. Trykk på Person details og endre Is deceased feltet til true.
5. På toppen inne på person kan du bare nå trykke på Account med samme navn, for så deretter velge en forespørsel.
6. Sjekk at det er et banner som sier at "Denne brukeren er død".

2022-10-19 08:34 UTC, JanRobertNav requested changes
Banner for død bruker vises ikke når isDeceased vises ikke når den er satt til true

2022-10-19 08:46 UTC, olsenrasmus commented
> 

jada jada. glemte å legge til filen :(

2022-10-19 08:51 UTC, JanRobertNav approved these changes

2022-10-24 06:57 UTC, vmjelde requested changes

2022-10-24 06:57 UTC, vmjelde commented on force-app/main/default/lwc/hot_isDeceasedBannerRequest/hot_isDeceasedBannerRequest.html
> +</template>
Det eksisterer allerede en banner på request vi kan benytte her. hot_warningBannerRequest

Legg til funksjonaliteten du har laget i denne komponenten.

2022-10-24 06:57 UTC, vmjelde commented on force-app/main/default/lwc/hot_isDeceasedBannerRequest/hot_isDeceasedBannerRequest.html
> +</template>
Fint om du bruker samme format med lightning-icon og <h2>

2022-10-24 06:57 UTC, vmjelde commented on force-app/main/default/lwc/hot_isDeceasedBannerRequest/hot_isDeceasedBannerRequest.js
> +        isDeceased({
Når du legger denne funksjonaliteten inn i eksisterende komponent, holder det om du utvider eksisterende getRecord-metode ved å importere referanse til feltet, og legge det til i fields-lista som argument.
avslutt med en get-metode for å rendre teksten basert på resultatet fra getRecord

2022-10-24 06:57 UTC, vmjelde commented on force-app/main/default/classes/HOT_RequestController.cls
> +}
Denne er ikke nødvendig ettersom vi gjenbruker eksisterende metode. Se kommentarer under

2022-10-24 06:57 UTC, vmjelde commented on force-app/main/default/flexipages/HOT_Request_Record_Page.flexipage-meta.xml
> +                <identifier>c_hot_isDeceasedBannerRequest</identifier>
Her har du fjernet eksisterende banner. Det var vel kanskje ikke ønskelig?

2022-10-24 07:00 UTC, vmjelde commented
Gi formidler tilgang til feltet

2022-10-24 12:26 UTC, vmjelde requested changes

2022-10-24 12:26 UTC, vmjelde commented on force-app/main/default/permissionsets/HOT_Tolk_Formidler.permissionset-meta.xml
> +        <editable>true</editable>
Skal de kunne redigere dette?? :O 
Er litt OP om formidlere skal kunne bringe folk tilbake til live...

2022-10-26 06:17 UTC, vmjelde approved these changes

2022-10-26 07:11 UTC, merged