Tolk 2119   se liste med relevante oppdrag på IR
navikt/crm-hot pull request #1430
Opened 2022-10-28 08:50 UTC by olsenrasmus

https://jira.adeo.no/browse/TOLK-2119
Hva er gjort:
Details fanen er flyttet helt til høyre.
Det er laget en ny tab "Relevante Oppdrag" som viser en liste med ALLE relevante oppdrag med samme oppdragstype og territorie som denne SA i Interested Resource også har. Om listen er tom vil det komme opp tekst som sier det ikke fantes noen flere relevante oppdrag.

IR= Interested Resource
Testing:

1. Gå inn på object manager. Iterested resource. Søk opp feltet Service resource. Trykk set-field-level-security og bare velg read og edit access på ALLE permission settene. 
2. Tror det finnes minst 2 service appointments. Endre disse SA til at alle disse har SAMME Service Territory.
3. Lag en interested Resource og velg en av SA-ene.
4. Om du trykker inn på denne Interested Resource og trykker Relevante Oppdrag vil du da få opp en liste med den andre SA. Sjekk at SA til denne IR ikke vises. Du kan se SA-navn i Details til høyre.
5. Deretter kan du trykke deg inn på den SA i listen som vises og endrer Service Territory til Tromso.
6. Trykk deretter inn på den IR du lagde og sjekk at det kommer opp tekst at ingen relevante oppdrag ble funnet.
7. Lag en ny request med en annen worktype (Altså ikke Tegnspråk), men samme Service Territory som SA til den i IR har. Gjør den om til en SA.
8. Sjekk at denne ikke kommer i listen over Relevante Oppdrag på IR

2022-10-31 06:14 UTC, JanRobertNav approved these changes

2022-11-04 07:15 UTC, vmjelde requested changes

2022-11-04 07:15 UTC, vmjelde commented on force-app/main/default/classes/HOT_ServiceAppointmentController.cls
> +public without sharing class HOT_ServiceAppointmentController {
with sharing

Prøv å finn et mer presist navn på klassen og metoden. HOT_InterestedResourceRecordPageController? Kanskje diskutere litt med Jan Robert?

2022-11-04 07:15 UTC, vmjelde commented on force-app/main/default/classes/HOT_ServiceAppointmentController.cls
> +    public static List<ServiceAppointment> getServiceAppointments(String recordId) {
Mer presist navn

2022-11-04 07:15 UTC, vmjelde commented on force-app/main/default/classes/HOT_ServiceAppointmentController.cls
> +                AND ServiceTerritoryId = :interestedResource.ServiceAppointment__r.ServiceTerritoryId
Litt usikker på om dette vil fungere slik som formidlerne ønsker, men tror ikke vi har noe valg her...
La oss gå for dette.

2022-11-04 07:15 UTC, vmjelde commented on force-app/main/default/lwc/hot_matchingServiceAppointmentsFromSA/hot_matchingServiceAppointmentsFromSA.html
> +        if:true={showList}
Om empty og showList alltid er det motsatte trenger vi vel bare én variabel?

2022-11-04 07:15 UTC, vmjelde commented on force-app/main/default/lwc/hot_matchingServiceAppointmentsFromSA/hot_matchingServiceAppointmentsFromSA.js
> +            fieldName: 'SAppointmentNumber',
SAppointmentNumber litt rart variabelnavn

2022-11-04 07:15 UTC, vmjelde commented on force-app/main/default/lwc/hot_matchingServiceAppointmentsFromSA/hot_matchingServiceAppointmentsFromSA.js
> +        },
Disse datetime feltene er blanke for åpne og released oppdrag. Bruk EarliestPermittedStart og DueDate istedenfor

2022-11-28 11:06 UTC, vmjelde approved these changes

2022-11-28 11:06 UTC, merged