Tolk 1452 ny versjon
navikt/crm-hot pull request #1465
Opened 2022-11-17 13:09 UTC by olsenrasmus

https://jira.adeo.no/browse/TOLK-1452

**### COMMUNITY**

**Hva har blitt gjort:**

Frilanstolker har ønsket å kunne endre tildelte oppdrag til dekket. Det er laget en flow som gjør dette og som er lagt til som en komponent i LWC (Winter’23). 

FØR: Oppdraget har sannsynligvis tomme verdier på faktisk start tid, og faktisk slutt tid. Status= Dispatched (Tildelt)

ETTER: Oppdraget skal ha fått faktisk start tid, faktisk slutt tid og status = Completed (Dekket) Er også mulighet for å velge avlyst av tolk/bruker.

Brukes samme flow som i mobil appen.
Ny versjon: Fikset slik at feltene oppdateres og knapp som var disabled fra start.  Lagt til Avbryt knapp.

**Testing:**

Gå til object manager -> interested resource -> feltet service resource.

Trykk set field level security og velg view og edit access på alle.

**Lag en frilans tolkbruker til community:**

License: Customer Community Plus
Profil: Nav Samhandler
Permission set group: HOT Tolk Frilans Gruppe
Permission set: HOT Tolk Frilans
Opprett Tjenesteressurs i HOT Admin → Service Resource → new

Koble til bruker du lagde i steget over
Huk av for at det er frilanstolk
Legg til ServiceTerritory Tromso
Preferred Regions: velg alle
Resource type: agent
Active: yes
Lag flere Oppdrag og tildel oppdraget til samme frilanstolk:

Gå inn på en service appointment.

Til høyre i boksen «assigned resources» trykk new under pil ikonet.

Velg service resource den du lagde.

Trykk save

Deretter trykker du på Status I service appointments details og velger Dispatched.

Lag 1 oppdrag med Time Constraints (tider i helt bunnen på oppdraget) i fremtiden.

Og 4 oppdrag med datoer/tider i fortiden.

**Test 1:**
Logg inn som frilanstolken i community

Trykk «oppdrag» og velg «mine oppdrag» tab. Trykk inn på et oppdrag og sjekk at du ikke kan trykke på knappen Endre status.

Gå tilbake

Trykk på filterikonet og fjern filteret som er der. DETTE MÅ DU GJØRE HVER GANG DU SKAL ENDRE OPPDRAG!

Gå inn på et oppdrag

Trykk på endre status knappen.

Velg at toggelen skal være aktiv og trykk endre.

Sjekk at oppdraget har fått samme også satt i faktisk tidene.

**Test 2:**

Gå tilbake og velg et annet oppdrag.

Velg at toggelen skal være inaktiv og velg selv eget tidspunkter.

Sjekk at det kommer feilmelding om faktisk start kommer etter faktisk slutt, og om det kommer feilmelding om faktisk slutt er satt til før faktisk start.

Trykk endre og se at verdien du skrev inn ble satt riktig. Du kan roefreshe siden for å sjekke dette.

Og du skal nå ikke kunne trykke på knappen Endre status.

**Test 3:**

Gå inn på et annet oppdrag og trykk Endre status. Noter deg oppdragsnummeret

Deretter gå tilbake til listen og gå inn på et annet oppdrag og trykk Endre status.

Velg et eller annet der.

Sjekk at DETTE oppdraget ble endret.

Sjekk at deretter at oppdraget med det oppdragsnummeret du norterte deg IKKE har blitt endret på.

Se til at det ser bra ut på mobil også.

2022-11-23 10:52 UTC, EdvardBrekke requested changes
Kan du se om du får til å vise en melding til tolk når status er endret?

2022-11-23 16:13 UTC, EdvardBrekke approved these changes

2022-11-28 11:47 UTC, vmjelde requested changes

2022-11-28 11:47 UTC, vmjelde commented on force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js
> +                    this.serviceAppointment.Status = 'None';
Disse feilmeldingene kan vi fjerne. Bare skjul hele flowen når den er ferdig.

2022-11-28 13:30 UTC, vmjelde requested changes

2022-11-28 13:30 UTC, vmjelde commented on force-app/main/default/flows/HOT_ChangeServiceAppointmentStatus.flow-meta.xml
> -    </decisions>
Dette skal vel ikke fjernes?

2022-11-28 13:30 UTC, vmjelde commented on force-app/main/default/flows/HOT_ChangeServiceAppointmentStatus.flow-meta.xml
> -    </recordLookups>
Dette skal nok ikke fjernes

2022-11-28 13:30 UTC, vmjelde commented on force-app/main/default/flows/HOT_ChangeServiceAppointmentStatus.flow-meta.xml
> -    </screens>
Dette skal ikke fjernes

2022-11-28 13:30 UTC, vmjelde commented on force-app/main/default/flows/HOT_ChangeServiceAppointmentStatus.flow-meta.xml
> -    </variables>
Dette skal ikke fjernes

2022-11-28 13:30 UTC, vmjelde commented on force-app/main/freelanceCommunity/lwc/hot_myServiceAppointments/hot_myServiceAppointments.js
> +                    this.serviceAppointment.Status = 'None';
Her kan man refaktorere koden og forkorte en del. holder det ikke å sette this.serviceAppointment.Status = data.Status?, i tillegg til de to booleanene? Trenger vel ikke disse tre if-setningene?

2022-11-28 14:09 UTC, vmjelde approved these changes

2022-11-30 06:51 UTC, merged