Erstattet Request_Initiator processbuilder [Må testes i uat]
navikt/crm-hot pull request #1520
Opened 2023-02-06 09:20 UTC by JanRobertNav

med HOT_Request_Initiator-flow

2023-02-15 12:17 UTC, chfosli commented on force-app/main/default/flows/HOT_Request_Initiator.flow-meta.xml
> +    <label>Request Initiator</label>
Legge til et mer beskrivende navn?

Hva med Request - Notify.....

2023-02-15 12:25 UTC, chfosli commented on force-app/main/default/flows/HOT_Request_Initiator.flow-meta.xml
> +    <recordLookups>
Henter ut id til CustomNotificationType? I så fall bør du endre navnet. Skjønner ikke helt spørringen heller for du filtrerer på Id = Record.Id, bør du ikke her hente ut CustomNotificationType basert på developerName?

2023-02-15 12:25 UTC, chfosli requested changes

2023-02-15 12:25 UTC, chfosli commented on force-app/main/default/flows/HOT_Request_Initiator.flow-meta.xml
> +        <name>RecipientIDs</name>
Trenger du denne? Kan du ikke sette det direkte i siste steg?

2023-06-07 05:32 UTC, EdvardBrekke approved these changes

2023-06-07 05:32 UTC, EdvardBrekke approved these changes

2023-06-07 06:14 UTC, merged