ThreadShare --> master
navikt/crm-hot pull request #1875
Opened 2023-11-20 14:21 UTC by EdvardBrekke

2023-11-20 14:58 UTC, chfosli requested changes

2023-11-30 14:02 UTC, chfosli commented on force-app/main/accessControl/classes/HOT_ThreadAccessHandler.cls
> +            threadIds.add(thread.Id);
Burde du ikke filtrere ut som logikken bare kjører på HOT-tråder?

2023-11-30 15:33 UTC, EdvardBrekke commented on force-app/main/accessControl/classes/HOT_ThreadAccessHandler.cls
> +            threadIds.add(thread.Id);
Oh yes ;)

2023-12-07 10:19 UTC, chfosli approved these changes

2023-12-07 11:13 UTC, merged