Tolk 1684 --> master
navikt/crm-hot pull request #966
Opened 2021-10-29 13:31 UTC by ebelegu

Opprettet egen flow 'Delete Content Document Link' som sletter ContentDocumentLink basert på valgte ContentDocument og den RecordId tilhørende Record man er i. 
Knyttet til knapp "Delete Files" i ServiceAppointment.

Erstattet Try-Catch med HOT_DatabaseOperations-metoden insertRecords() I HOT_ContentDocumentLinkService linje 21.

https://jira.adeo.no/browse/TOLK-1684

2021-11-03 08:25 UTC, vmjelde requested changes

2021-11-03 08:25 UTC, vmjelde commented on force-app/main/default/classes/HOT_ContentDocumentLinkService.cls
> +    public static void getContentDocumentLink(List<HOT_ContentDocumentLinkService> inputValue) {
metodenavn er misvisende. Burde kanskje hete deleteContentDocumentLinks?

2021-11-03 08:25 UTC, vmjelde commented on force-app/main/default/quickActions/ServiceAppointment.Delete_Files.quickAction-meta.xml
> +    <flowDefinition>HOT_DeleteContentDocument</flowDefinition>
Dette er vel ikke riktig flow?
Testa i scratch org, og da ble hele fila sletta. Dette er nok årsaken.

2021-11-03 13:49 UTC, ebelegu commented on force-app/main/default/classes/HOT_ContentDocumentLinkService.cls
> +    public static void getContentDocumentLink(List<HOT_ContentDocumentLinkService> inputValue) {
Skulle nok egentlig det ja, fikser nå :)

2021-11-10 07:18 UTC, vmjelde approved these changes

2021-11-10 07:18 UTC, merged