Tolk 1055+1565
navikt/crm-hot pull request #978
Opened 2021-11-04 08:13 UTC by EirikFladby

https://jira.adeo.no/browse/TOLK-1055
https://jira.adeo.no/browse/TOLK-1565

2021-11-04 11:14 UTC, vmjelde requested changes

2021-11-04 11:14 UTC, vmjelde commented on force-app/main/userCommunity/lwc/hot_requestForm_company/hot_requestForm_company.js
> -        AdditionalInvoiceText__c: ''
Hvorfor har du fjernet denne? Det er jo fortsatt et felt her.

2021-11-04 11:14 UTC, vmjelde commented on force-app/main/userCommunity/lwc/hot_requestForm_company/hot_requestForm_company.js
> +    isCompanyEconomicProvider = false;
Er denne unødvendig? burde vel kunne bare bruke fieldValues.IsOtherEconomicProvider__c?

2021-11-04 11:14 UTC, vmjelde commented on force-app/main/userCommunity/lwc/hot_requestForm_orderer/hot_requestForm_orderer.css
> +    padding: 2rem 2rem 1rem 2rem;
Se kommentar over

2021-11-04 11:14 UTC, vmjelde commented on force-app/main/userCommunity/lwc/hot_requestForm_request/hot_requestForm_request.css
> +    padding: 2rem 2rem 1rem 2rem;
Se kommentar over

2021-11-04 11:14 UTC, vmjelde commented on force-app/main/userCommunity/lwc/hot_requestForm_type/hot_requestForm_type.js
> -    }
Vanskelig å se hva som har skjedd, men ser riktig ut. Så jo også hvordan det så ut, og så bra ut.
Kan du legge til 'Me' som default? (da slipper vi også validering på Neste-knapp-klikk)

2021-11-04 11:14 UTC, vmjelde commented on force-app/main/userCommunity/lwc/hot_requestForm_user/hot_requestForm_user.css
> +    padding: 2rem 2rem 1rem 2rem;
Se kommentar over.

2021-11-04 15:34 UTC, EirikFladby commented on force-app/main/userCommunity/lwc/hot_requestForm_company/hot_requestForm_company.js
> -        AdditionalInvoiceText__c: ''
Skjedd en feil gitt

2021-11-10 07:22 UTC, vmjelde approved these changes

2021-11-12 09:31 UTC, merged