Tolk 1721 --> master
navikt/crm-hot pull request #985
Opened 2021-11-11 15:04 UTC by ebelegu

Navn på tolker vises i statusoppdatering-SMS.

Siste tolk etterfølges av punktum, med kommaskille mellom flere tolker.

https://jira.adeo.no/browse/TOLK-1721

2021-11-19 09:00 UTC, vmjelde requested changes
Tolknavn på en WorkOrder hentes ut et par steder nå, og jeg tror vi skal vurdere å ha et felt på WorkOrder som vi fyller ut med tildelte tolker.
Det blir da en trikker på ServiceAppointment som oppdaterer feltet på WorkOrder.
Metoden som utfører oppdateringen burde kunne bli kalt på via en batch-klasse, slik ta man kan kjøre oppdatering av eksisterende data. 

Er dette noe du kunne tenkt deg å gjøre? Tenker vi tar ut dette du gjør her, men på sikt bruke feltet på WorkOrder.

2021-11-23 09:15 UTC, ebelegu commented on force-app/main/sms/classes/HOT_ReminderSMSService.cls
> +        Map<Id, String> tolkNames = tolkNamesByWorkOrderId(workOrderList);
Fikset

2021-11-23 09:16 UTC, ebelegu commented on force-app/main/sms/classes/HOT_ReminderSMSService.cls
> +        Map<Id, String> tolkNamesByWorkOrderIds = new Map<Id, String>();
Fikset

2021-11-23 09:16 UTC, ebelegu commented on force-app/main/sms/classes/HOT_ReminderSMSService.cls
> +            Id workOrderId = workOrder.Id;
Fikset

2021-11-23 09:16 UTC, ebelegu commented on force-app/main/sms/classes/HOT_ReminderSMSService.cls
>          message = message.removeEnd(', ');
Fikset

2021-11-23 09:27 UTC, ebelegu commented on force-app/main/sms/classes/HOT_ReminderSMSServiceTest.cls
> +    static void sendSMSToOrdererOnStatusUpdateTest4() {
Fikset

2021-11-23 09:27 UTC, ebelegu commented on force-app/main/sms/classes/HOT_ReminderSMSServiceTest.cls
> +    static void sendSMSToOrdererOnStatusUpdateTest3() {
Fikset

2021-11-23 09:31 UTC, ebelegu commented on force-app/main/sms/classes/HOT_ReminderSMSServiceTest.cls
> +        String smsPhoneNumber = smsList[0].Recipient__c;
Fikset

2021-11-23 09:31 UTC, ebelegu commented on force-app/main/sms/classes/HOT_ReminderSMSServiceTest.cls
> +        ServiceResource tolk = tolks[0];
Fikset

2021-11-23 09:41 UTC, ebelegu commented on force-app/main/sms/classes/HOT_ReminderSMSService.cls
> +                }
Fikset

2021-11-23 09:41 UTC, ebelegu commented on force-app/main/sms/classes/HOT_ReminderSMSService.cls
> +            String tolkNames = 'Tolk er: ';
Fikset

2021-11-23 09:51 UTC, ebelegu commented on force-app/main/sms/classes/HOT_ReminderSMSService.cls
> +    private static Map<Id, List<ServiceAppointment>> serviceAppointmentsByWorkOrderId(List<WorkOrder> workOrders) {
Fikset

2021-11-24 09:12 UTC, vmjelde requested changes

2021-11-24 09:12 UTC, vmjelde commented on force-app/main/sms/classes/HOT_ReminderSMSService.cls
> +        message += interpreterNames;
Her må du vel legge til "Tolk er: "

2021-11-24 09:12 UTC, vmjelde commented on force-app/main/sms/classes/HOT_ReminderSMSServiceTest.cls
>          System.assert(message.contains('TolkName'), 'Could not create sms-record');
Du endter vel til 'InterpreterName'?

2021-11-28 08:44 UTC, vmjelde approved these changes

2021-11-29 07:11 UTC, merged